# Site settings
title: Data Visulization Portfolio
tag_text: Good Clean Read
description: Final Portfolio for INTEG 375
url: "http://127.0.0.1:4000"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
